package emosh;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.squareup.javapoet.*;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;
import java.util.*;

/**
 * Maven goal to generate Spring Boot RuntimeHints automatically by comparing
 * baseline and full reflection configuration files generated by GraalVM agent.
 */
@Mojo(name = "generate", defaultPhase = LifecyclePhase.GENERATE_SOURCES)
public class HintMojo extends AbstractMojo {

    /**
     * Path to the baseline reflect-config.json (Application startup only).
     */
    @Parameter(defaultValue = "${project.basedir}/src/main/resources/META-INF/native-image/baseline-reflect.json")
    private File baselineJson;

    /**
     * Path to the full reflect-config.json (Application with all features executed).
     */
    @Parameter(defaultValue = "${project.basedir}/src/main/resources/META-INF/native-image/reflect-config.json")
    private File fullJson;

    /**
     * Directory where the generated Java source file will be stored.
     */
    @Parameter(defaultValue = "${project.build.directory}/generated-sources/annotations")
    private File outputDir;

    @Override
    public void execute() throws MojoExecutionException {
        if (!fullJson.exists()) {
            getLog().error("reflect-config.json not found! Please run the GraalVM agent to collect metadata.");
            return;
        }

        try {
            ObjectMapper mapper = new ObjectMapper();
            Set<String> baselineNames = new HashSet<>();

            if (baselineJson.exists()) {
                List<Map<String, Object>> baselineList = mapper.readValue(baselineJson, List.class);
                for (Map<String, Object> item : baselineList) {
                    baselineNames.add((String) item.get("name"));
                }
                getLog().info("Baseline loaded: " + baselineNames.size() + " classes will be filtered.");
            } else {
                getLog().warn("Baseline file not found. All discovered classes will be added to RuntimeHints.");
            }

            List<Map<String, Object>> fullList = mapper.readValue(fullJson, List.class);
            generateDiffSource(fullList, baselineNames);

            getLog().info("Native Hint automation completed successfully. Source file generated.");
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to generate hint source code: " + e.getMessage(), e);
        }
    }

    private void generateDiffSource(List<Map<String, Object>> fullList, Set<String> baseline) throws IOException {
        ClassName runtimeHints = ClassName.get("org.springframework.aot.hint", "RuntimeHints");
        ClassName registrar = ClassName.get("org.springframework.aot.hint", "RuntimeHintsRegistrar");
        ClassName typeRef = ClassName.get("org.springframework.aot.hint", "TypeReference");
        ClassName memberCat = ClassName.get("org.springframework.aot.hint", "MemberCategory");

        MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder("registerHints")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(runtimeHints, "hints")
                .addParameter(ClassLoader.class, "classLoader");

        int count = 0;
        for (Map<String, Object> item : fullList) {
            String className = (String) item.get("name");

            if (!baseline.contains(className)) {
                methodBuilder.addStatement(
                        "hints.reflection().registerType($T.of($S), builder -> builder.withMembers($T.INVOKE_PUBLIC_CONSTRUCTORS, $T.INVOKE_PUBLIC_METHODS))",
                        typeRef, className, memberCat, memberCat
                );
                count++;
            }
        }

        getLog().info("Identified " + count + " unique classes for RuntimeHints registration.");

        TypeSpec hintClass = TypeSpec.classBuilder("GeneratedNativeHints")
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(registrar)
                .addMethod(methodBuilder.build())
                .build();

        JavaFile javaFile = JavaFile.builder("emosh.generated", hintClass).build();
        javaFile.writeTo(outputDir);
    }
}